<?php
return array (
  0 => 
  array (
    'id' => '43',
    'catid' => '52',
    'typeid' => '0',
    'title' => '自然科学2',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0613/20170613105049610.jpg',
    'keywords' => '',
    'description' => '让生活更加简单，让生命更加安全。让生活更加简单，让生命更加安全。让生活更加简单，让生命更加安全。',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=52&id=43',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1497365506',
    'updatetime' => '1497365557',
    'redirect_url' => '',
    'content' => '<span style="color: rgb(51, 51, 51); font-family: \'microsoft yahei\'; font-size: 15px; line-height: 22px;">让生活更加简单，让生命更加安全。让生活更加简单，让生命更加安全。让生活更加简单，让生命更加安全。</span>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'muti_image' => '',
  ),
);
?>