<?php
return array (
  30 => 
  array (
    'id' => '30',
    'catid' => '41',
    'typeid' => '0',
    'title' => '推动“一带一路”沿线文化交流合作“丝路荟影”摄影展在北京举行',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0614/20170614091817910.jpg',
    'keywords' => '',
    'description' => '创新改变生活',
    'posids' => '1',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=41&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496852023',
    'updatetime' => '1496852136',
    'redirect_url' => '',
    'hitsid' => 'c-1-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '41',
    'typeid' => '0',
    'title' => '推动“一带一路”沿线文化交流合作“丝路荟影”摄影展在北京举行',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0603/20170603094254562.jpg',
    'keywords' => '',
    'description' => '创新改变生活',
    'posids' => '1',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=41&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1483200000',
    'updatetime' => '1496935620',
    'redirect_url' => '',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  48 => 
  array (
    'id' => '48',
    'catid' => '41',
    'typeid' => '0',
    'title' => '推动“一带一路”沿线文化交流合作“丝路荟影”摄影展在北京举行',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0614/20170614015217600.jpg',
    'keywords' => '',
    'description' => '在“一带一路”国际合作高峰论坛召开之际，由丝路商旅文组委会等单位主办的“丝路荟影”摄影展在北京拉开帷幕，全国人大原副委员长蒋正华、全国政协原副主席李金华等领导同志，以及海内外华人摄影艺术家和各界人士出席了5月12日的开幕式。',
    'posids' => '1',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=41&id=48',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1497368585',
    'updatetime' => '1497368605',
    'redirect_url' => '',
    'hitsid' => 'c-1-48',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  49 => 
  array (
    'id' => '49',
    'catid' => '41',
    'typeid' => '0',
    'title' => '推动“一带一路”沿线文化交流合作“丝路荟影”摄影展在北京举行',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '在一带一路国际合作高峰论坛召开之际，由丝路商旅文组委会等单位主办的丝路荟影摄影展在北京拉开帷幕，全国人大原副委员长蒋正华、全国政协   ',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=41&id=49',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1497368609',
    'updatetime' => '1497368637',
    'redirect_url' => '',
    'hitsid' => 'c-1-49',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  50 => 
  array (
    'id' => '50',
    'catid' => '41',
    'typeid' => '0',
    'title' => '推动“一带一路”沿线文化交流合作“丝路荟影”摄影展在北京举行',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '在“一带一路”国际合作高峰论坛召开之际，由丝路商旅文组委会等单位主办的“丝路荟影”摄影展在北京拉开帷幕，全国人大原副委员长蒋正华、全国政协原副主席李金华等领导同志，以及海内外华人摄影艺术家和各界人士出席了5月12日的开幕式。',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=41&id=50',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1497368659',
    'updatetime' => '1497368689',
    'redirect_url' => '',
    'hitsid' => 'c-1-50',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>