<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '27',
    'typeid' => '0',
    'title' => '浔阳村小学生活公益活动',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0606/20170606124931367.png',
    'keywords' => '浔阳村小学生活公益活动',
    'description' => '浔阳村小学生活公益活动',
    'posids' => '1',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=27&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496724466',
    'updatetime' => '1496724586',
    'redirect_url' => '',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '27',
    'typeid' => '0',
    'title' => '第二个文章',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0606/20170606124931367.png',
    'keywords' => '第二个文章',
    'description' => '大学生社会公益实践活动由大学生发起或参与，以利他为内容，以公共利益为目标指向。大学生社会公益实践是服务社群的一种方式，也是大学生观   ',
    'posids' => '1',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=27&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496724599',
    'updatetime' => '1496724637',
    'redirect_url' => '',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '28',
    'typeid' => '0',
    'title' => '社会活动1',
    'style' => '',
    'thumb' => '',
    'keywords' => '社会活动1',
    'description' => '社会活动1',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=28&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496725415',
    'updatetime' => '1496725468',
    'redirect_url' => '',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '28',
    'typeid' => '0',
    'title' => '社会活动2',
    'style' => '',
    'thumb' => '',
    'keywords' => '社会活动2',
    'description' => '社会活动2',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=28&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496726112',
    'updatetime' => '1496726132',
    'redirect_url' => '',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>