<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '15',
    'typeid' => '0',
    'title' => '新闻频道测试1',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0603/20170603102849984.jpg',
    'keywords' => '创新改变生活',
    'description' => '创新改变生活',
    'posids' => '1',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=15&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496500033',
    'updatetime' => '1496500137',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '15',
    'typeid' => '0',
    'title' => '创新改变生活2',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0603/20170603103623444.jpg',
    'keywords' => '创新改变生活2',
    'description' => '创新改变生活2',
    'posids' => '1',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=15&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496500542',
    'updatetime' => '1496500587',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>