<?php
return array (
  24 => 
  array (
    'id' => '24',
    'catid' => '37',
    'typeid' => '0',
    'title' => '北京海生泰和医药科技有限公司',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0607/20170607010139979.jpg',
    'keywords' => '',
    'description' => '成立于2015年12月，由留英药学博士，及其来自于制药，能源，电子等行业的伙伴共同创立，致力于采用创新性的药品和食品制剂技术，为中国消费者研究、开发和生产日化品、食品、营养品、药',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=37&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496811581',
    'updatetime' => '1496811645',
    'redirect_url' => '',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '37',
    'typeid' => '0',
    'title' => '目前',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0607/20170607010322726.jpg',
    'keywords' => '',
    'description' => '已在英国伦敦设立了分公司，在中国北京建立研发中心，并初步创立了由国内外知名专家学者和国内资深博士、研究员共同建立的技术研发团队。',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=37&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496811752',
    'updatetime' => '1496811806',
    'redirect_url' => '',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  47 => 
  array (
    'id' => '47',
    'catid' => '37',
    'typeid' => '0',
    'title' => '我们相信“中国制造”的力量',
    'style' => '',
    'thumb' => 'http://healstec.itcask.com/uploadfile/2017/0613/20170613112827312.jpg',
    'keywords' => '',
    'description' => '扎根中国，与国内外的科研院所和科技公司进行广泛的技术合作，在全球范围内选取创造性的技术方案和优质原料、辅料，参照中国人的健康数据及   ',
    'posids' => '0',
    'url' => 'http://healstec.itcask.com/index.php?m=content&c=index&a=show&catid=37&id=47',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1497367679',
    'updatetime' => '1497367747',
    'redirect_url' => '',
    'hitsid' => 'c-1-47',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>