<?php
return array (
  31 => 
  array (
    'id' => '31',
    'catid' => '23',
    'typeid' => '0',
    'title' => '纳米乳液的制备方法及原理',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '纳米乳液（nanoemulsion）又称微乳液（microemulsion），是由水、油、表面活性剂和助表面活性剂等自发形成，粒径为1～100nm的热力学稳定、   ',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=23&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496897581',
    'updatetime' => '1496897676',
    'redirect_url' => '',
    'hitsid' => 'c-1-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '24',
    'typeid' => '0',
    'title' => '微乳剂',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0608/20170608010353110.png',
    'keywords' => '',
    'description' => '为了更好地实现我们的愿景，为我们的家人和顾客开发更有效，更便捷，更安全，更具依从性的健康产品和服务，我们在北京建立了研发中心，配备   ',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=24&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496898117',
    'updatetime' => '1496898243',
    'redirect_url' => '',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '24',
    'typeid' => '0',
    'title' => '脂质体',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0608/20170608010353110.png',
    'keywords' => '',
    'description' => '为了更好地实现我们的愿景，为我们的家人和顾客开发更有效，更便捷，更安全，更具依从性的健康产品和服务，我们在北京建立了研发中心，配备   ',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=24&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496898260',
    'updatetime' => '1496898299',
    'redirect_url' => '',
    'hitsid' => 'c-1-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '25',
    'typeid' => '0',
    'title' => '食品级日化',
    'style' => '',
    'thumb' => 'http://www.healstec.com/uploadfile/2017/0608/20170608022730733.png',
    'keywords' => '',
    'description' => '内容内容',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=25&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496903197',
    'updatetime' => '1496903259',
    'redirect_url' => '',
    'hitsid' => 'c-1-34',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '26',
    'typeid' => '0',
    'title' => '纳米乳液的制备方法及原理',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '纳米乳液的制备方法及原理纳米乳液的制备方法及原理纳米乳液的制备方法及原理纳米乳液的制备方法及原理纳米乳液的制备方法及原理纳米乳液的   ',
    'posids' => '0',
    'url' => 'http://www.healstec.com/index.php?m=content&c=index&a=show&catid=26&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'healstec',
    'inputtime' => '1496903537',
    'updatetime' => '1496903547',
    'redirect_url' => '',
    'hitsid' => 'c-1-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>